name: Run Python Tests

on: [push]

jobs:
  pytest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          pytest tests/ --junitxml=report.xml

