jobs:
  pytest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install pip and dependencies
        run: |
          python3 -m ensurepip --upgrade || curl -O https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py
          python3 -m pip install pytest

      - name: Run Tests
        run: |
          python3 -m pytest tests/ --junitxml=report.xml

